# The URL the site will be built for
base_url = "https://www.neversaw.us"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Chris Dickinson"

theme = "neversawus"
feed_filenames = ["rss.xml"]

taxonomies = [{ name = "tags", feed = true }]


generate_feeds = true

[slugify]
paths = "off"

[extra]
# Put all your custom variables here

[markdown]
bottom_footnotes = false
github_alerts = true
smart_punctuation = true
definition_list = true

[markdown.highlighting]
# TODO: move from inline to classes.
theme = "everforest-dark"
