name: "Receive dropbox events"
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [latest]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  receive_dropbox_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            bin/zola
          key: bin/zola
      - name: download zola
        run: |
          bin/install.sh

      - name: download likelike
        run: |
          gh release download --repo chrisdickinson/likelike -p '*x64_linux*'
          <likelike*.tar.gz tar zxv -C /usr/local/bin
          mkdir -p ~/.local/share
        env:
          GH_TOKEN: ${{ github.token }}

      - name: download dropbox blog
        run: |
          bin/download_folder.sh ${{ secrets.DROPBOX_KEY }}
          mv blog/likelike.sqlite3 ~/.local/share/ || true
          mv blog/static/* static
          mv blog/* content

      - name: run likelike export
        run: |
          mkdir -p content/links
          likelike export content/links

      - name: 'build the blog, BE THE BLOG'
        run: |
          bin/zola build --output-dir output
      - name: upload the blog
        run: |
          cd output
          aws s3 sync . s3://www.neversaw.us/ --acl public-read
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-west-2
      - name: purge cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
          -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
